Repository Codein-Labs/ibexa-seo-toolkit, pull requests merged in 2021-09, with the labels that each got.

#8 [CI] Set up GitHub Actions workflow
  .github/workflows/ci.yaml
  .php-cs-fixer.php
  CHANGELOG.md
  bundle/Analysis/AbstractAnalyzer.php
  bundle/Analysis/Analyzers/InternalLinksAnalyzer.php
  bundle/Analysis/Analyzers/KeywordInTitlesAnalyzer.php
  bundle/Analysis/Analyzers/KeywordInUrlSlugAnalyzer.php
  bundle/Analysis/Analyzers/MetaDescriptionContainsKeywordAnalyzer.php
  bundle/Analysis/Analyzers/OutboundLinksAnalyzer.php
  bundle/Analysis/Analyzers/SeoTitleWidthAnalyzer.php
  bundle/Analysis/Analyzers/TitleTagContainsKeywordAnalyzer.php
  bundle/Analysis/Analyzers/WordCountAnalyzer.php
  bundle/Analysis/ParentAnalyzerService.php
  bundle/Controller/AnalyzeContentController.php
  bundle/Controller/GetRobotsController.php
  bundle/Controller/SitemapController.php
  bundle/DependencyInjection/Configuration.php
  bundle/EventListener/ContentCreateEditRightMenuListener.php
  bundle/EventListener/PageBuilderMenuListener.php
  bundle/EventListener/SitemapResponseListener.php
  bundle/Exception/ValidationException.php
  bundle/FieldType/Converter.php
  bundle/FieldType/Type.php
  bundle/FieldType/Value.php
  bundle/Form/DataTransformer/FieldArrayToObjectTransformer.php
  bundle/Form/Type/AnalysisDTOType.php
  bundle/Form/Type/ContentConfigurationType.php
  bundle/Helper/SiteAccessConfigResolver.php
  bundle/Helper/SitemapQueryHelper.php
  bundle/Model/AnalysisDTO.php
  bundle/Model/ArrayableInterface.php
  bundle/Model/Field.php
  bundle/Resources/config/services.yaml
  bundle/Service/SitemapContentService.php
  bundle/Twig/CodeinIbexaSeoExtension.php
  bundle/templates/content_type/view.html.twig
  bundle/templates/seo_menu.html.twig
  bundle/templates/sitemap/sitemap.xsl.twig
  composer.json
  pslam.xml.dist
  tests/bundle/Analysis/Analyzers/WordCountAnalyzerTest.php
  tests/bundle/Controller/GetRobotsControllerTest.php
  tests/bundle/DependencyInjection/Compiler/AnalyzerPassTest.php
  tests/bundle/DependencyInjection/ConfigurationTest.php
  tests/bundle/DependencyInjection/ExtensionTest.php
Labels: enhancement

#7 Fix/analyzer tag autoconfiguration and sitemap query event
  CHANGELOG.md
  bundle/Event/SitemapQueryEvent.php
  bundle/EventSubscriber/SitemapQueryEventSubscriber.php
  bundle/Helper/SitemapQueryHelper.php
  bundle/IbexaSeoToolkitBundle.php
  bundle/Resources/config/services.yaml
  docs/usage/SITEMAP.md
Labels: enhancement

#6 Fix/url slug analyser without richtext and sitemap
  CHANGELOG.md
  bundle/Analysis/Analyzers/KeywordInUrlSlugAnalyzer.php
  bundle/Event/SitemapQueryEvent.php
  bundle/EventSubscriber/SitemapQueryEventSubscriber.php
  bundle/Helper/SitemapQueryHelper.php
  bundle/Service/SitemapContentService.php
Labels: enhancement

#3 Update DoctrineMigrations path. Improve install documentation
  .php-cs-fixer.php
  CHANGELOG.md
  bundle/migrations/Version20210304163313.php
  docs/INSTALL.md
  pslam.xml.dist
Labels: documentation, installation

#1 Fix/title and description analyzers
  CHANGELOG.md
  bundle/Analysis/Analyzers/MetaDescriptionContainsKeywordAnalyzer.php
  bundle/Analysis/Analyzers/TitleTagContainsKeywordAnalyzer.php
Labels: enhancement

#2 Append SEO toolkit button in the same way on page builder contents
  CHANGELOG.md
  bundle/EventListener/AbstractToolbarMenuListener.php
  bundle/EventListener/ContentCreateEditRightMenuListener.php
  bundle/EventListener/PageBuilderMenuListener.php
Labels: enhancement

#9 [Assets] Use ezplatform entrypoint for assets import
  CHANGELOG.md
  bundle/Resources/encore/codein.config.js
  bundle/Resources/encore/ez.config.js
  bundle/templates/seo_menu.html.twig
  docs/INSTALL.md
Labels: enhancement, installation
